# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm audit

on:
  pull_request:
    branches:  
      - dev
    paths:
      - 'lib/**/*'
      - 'extensions/**/*'
      - '**/package-lock.json'
      - '!**.md'
      - '.github/workflows/npm-audit.yml'
  merge_group:
    types: [checks_requested]

concurrency:
  group: audit-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit-root:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: npm audit (root)
      run: npm audit --workspace=lib/** --workspace=extensions/** --include-workspace-root --omit=dev
